version: 2.1
jobs:
  deploy:
    machine:
      image: windows-server-2019-vs2019:stable
    resource_class: windows.medium
    steps:
    #- checkout
    - run:
        shell: powershell.exe -ExecutionPolicy Bypass
        name: "Test"
        command: |
            $deployment = $(curl -X GET "http://toan0701.ddns.net:9080/Nococid/api/Listeners/CircleCI/deployment?tool_name=Azure&project_id=5c8dd234-79e9-4043-575c-08d906487b7c" -H  "accept: application/json")
            echo $deployment
workflows:
  version: 2.1
  workflow:
    jobs:
      - deploy
