version: 2.1
jobs:
  deploy:
    machine:
      image: windows-server-2019-vs2019:stable
    resource_class: windows.medium
    steps:
      - checkout
      - run:
          shell: powershell.exe -ExecutionPolicy Bypass
          name: "Deploy"
          command: |
              remove-item alias:\curl
              $deployment = $(curl -X GET "http://toan0701.ddns.net:9080/Nococid/api/Listeners/CircleCI/deployment?tool_name=Azure&project_id=33ab2d2d-ab0e-44e8-e5fa-08d922e39241" --header "Accept:application/json")
              $json = ConvertFrom-Json $deployment
              $username = 'http://' + $json.psUsername
              $password = ConvertTo-SecureString $json.psPassword -AsPlainText -Force
              $creds = New-Object System.Management.Automation.PSCredential -ArgumentList ($username, $password)
              Connect-AzureRmAccount -Credential $creds -Tenant $json.deployment.tenant -ServicePrincipal
              try {
                  Get-AzureRmWebApp -ResourceGroupName $json.deployment.resourceGroupName -Name "Stagging-NococidAPI" -ErrorAction Stop
              } catch {
                  New-AzureRmWebApp -ResourceGroupName $json.deployment.resourceGroupName -Name "Stagging-NococidAPI" -AppServicePlan $json.deployment.appSerivcePlan
              }
              echo "ddd"
              Get-AzureRmWebAppPublishingProfile -OutputFile "C:\Users\circleci\project\publishprofile.xml" -Format WebDeploy -ResourceGroupName $json.deployment.resourceGroupName -Name "Stagging-NococidAPI"
              Stop-AzureRmWebApp -ResourceGroupName $json.deployment.resourceGroupName -Name "Stagging-NococidAPI"
              dotnet publish ./Manage_Projects_API/Manage_Projects_API.csproj -c Release -o app-publish --self-contained false
              New-Item -Path . -Name "artifacts" -ItemType "directory"
              Compress-Archive -Path ./app-publish/* -DestinationPath ./artifacts/draft.zip
              & "C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" @('-verb:sync', '-source:contentPath=C:\Users\circleci\project/app-publish', '-dest:contentPath=d:\home\site\wwwroot\,publishSettings=C:\Users\circleci\project\publishprofile.xml')
workflows:
  version: 2.1
  workflow:
    jobs:
      - deploy
