version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  deploy:
    executor: win/default
    resource_class: windows.medium
    steps:
      - checkout
      - run:
          shell: powershell.exe -ExecutionPolicy Bypass
          name: "Deploy"
          command: |
              Get-InstalledModule
workflows:
  version: 2.1
  workflow:
    jobs:
      - deploy
