version: 2.1
jobs:
  deploy:
    machine:
      image: windows-server-2019-vs2019:stable
    resource_class: windows.medium
    steps:
    #- checkout
    - run:
        shell: powershell.exe -ExecutionPolicy Bypass
        name: "Deploy"
        command: |
            Install-Module -Name Az.Websites -Force -RequiredVersion 2.6.0
workflows:
  version: 2.1
  workflow:
    jobs:
      - deploy
